version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: pots-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: potsdevdb
  